### PR TITLE
Fix for 400 response from Github API

### PR DESCRIPTION
**Pull request by nikita-d**
An error can be observed when trying to render text containing unicode characters (Cyrillic for example). To fix it, I have modified `gh-md--json-payload` function to encode payload in UTF-8.

### CODE REVIEW

**Comment by nikita-d** [comment]
Emacs-snapshot job fails due to inability to install Cask:

https://travis-ci.org/nikita-d/gh-md.el/jobs/92237099

**Comment by PuercoPop** [comment]
First let me thank you for your interest in gh-md.el. I should clarifiy I am not the author or mantainer, that would be @marsam

I am sorry I was not more clear earlier, f9bde84 added a header package-version which collides with the version header. Both [headers are allowed but not both](https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html), more so with different versions. This is not of course a substantive objection but one of form.

**Comment by nikita-d** [comment]
I have removed package-version header. That's my first pull request ever, still figuring out things.

What can I do make emacs-snapshot build pass? Error seems completely unrelated to my modifications.

**Comment by marsam** [comment]
Hi:
Thanks for the pull request, before merge it, could you please squash the commits.

Also, don't worry about travis-ci the build is currently broken.

**Comment by PuercoPop** [comment]
@nikita-d Sorry for the delay. I just squashed the commits before merging (making sure you retained authorship). Thanks for the contribution.

**Comment by nikita-d** [comment]
Wow, somehow I've missed the whole thread. Sorry.

**Pull request closed without merging**
